### ISSUE TITLE
[BUG] missing "webmozart/assert" dependency (composer --no-dev)

### ISSUE THREAD

**Issue by Fahl-Design** [laminas/laminas-hydrator#63]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 4.2.0 (maybe more)

#### Summary

missing dependency
`"webmozart/assert": "^1.10"`

#### Current behavior

usage of missing dependency:

https://github.com/laminas/laminas-hydrator/blob/54599e5046158979592e702401c76f1512020f7f/src/ClassMethodsHydrator.php#L9

#### How to reproduce

composer update --no-dev

#### Expected behavior

not break my code ;)

#### Suggestion

add composer-require-checker to QA (i know it's a pain to setup)

**Comment by Ocramius** [comment]
Hey @Fahl-Design, can you send a patch for this perhaps? Should be a bugfix for the `4.2.x` branch...

**Comment by Fahl-Design** [comment]
Hey @Ocramius, jup patch incoming :)

**Comment by Ocramius** [comment]
@Fahl-Design it's released BTW :)

**Comment by Fahl-Design** [comment]
@Ocramius Thx for your ultra quick reaction and community support!
