### ISSUE TITLE
Breakage with latest servicemanager and psr/container v2

### ISSUE THREAD

**Issue by remicollet** [laminas/laminas-hydrator#92]
`PHP Fatal error:  Declaration of Laminas\Hydrator\StandaloneHydratorPluginManager::has($id) must be compatible with Psr\Container\ContainerInterface::has(string $id): bool in /dev/shm/BUILDROOT/php-laminas-hydrator4-4.5.0-1.fc35.remi.x86_64/usr/share/php/Laminas/Hydrator4/StandaloneHydratorPluginManager.php on line 97
`

**Comment by Ocramius** [comment]
@boesing WDYT? Full revert of https://github.com/laminas/laminas-servicemanager/pull/127 ?

**Comment by Ocramius** [comment]
Ref: https://github.com/laminas/laminas-servicemanager/pull/147

**Comment by Ocramius** [comment]
https://github.com/laminas/laminas-servicemanager/releases/tag/3.15.1 should fix this: sad to see that work reverted, but our hopes that it would work were unfounded.
